imports:
- { resource: ./inventis_translationbundle/services-storage.yml }
- { resource: ./inventis_translationbundle/services-catalogue-caching.yml }
- { resource: ./inventis_translationbundle/services-commands.yml }
- { resource: ./inventis_translationbundle/services-specification-satisfying-providers.yml }
- { resource: ./inventis_translationbundle/services-import.yml }
- { resource: ./inventis_translationbundle/services-export.yml }
- { resource: ./inventis_translationbundle/services-brick.yml }

parameters:
    inventis_translation.symfony_translation_cache_directory: "%kernel.cache_dir%/translations"
    inventis_translation.cache_directory: "%inventis_translation.symfony_translation_cache_directory%/stored"

services:
    inventis_translation.translation_loader.doctrine:
        class: Inventis\Bundle\TranslationBundle\DoctrineTranslationLoader
        arguments:
        - '@inventis_translation.specification_satisfying_translation_key_translation_provider'
        tags:
        # Alias is still required to identify the format, even though we don't load from files, see
        # https://symfony.com/doc/current/reference/dic_tags.html#translation-loader
        -
            name: 'translation.loader'
            alias: !php/const Inventis\Bundle\TranslationBundle\DoctrineTranslationLoader::FORMAT

    inventis_translation.doctrine_message_catalogue_factory:
        class: Inventis\Bundle\TranslationBundle\DoctrineMessageCatalogueFactory
        arguments:
        - '@inventis_translation.specification_satisfying_doctrine_translation_key_provider'
        - '@inventis_translation.specification_satisfying_doctrine_translation_domain_provider'
        - '@inventis_translation.specification_satisfying_doctrine_translation_key_translation_provider'
        - '@inventis_translation.doctrine_resource'

    inventis_translation.translation_storing_translator:
        class: Inventis\Bundle\TranslationBundle\TranslationStoringTranslator
        decorates: translator.default
        arguments:
        - '@inventis_translation.translation_storing_translator.inner'
        - '@translator.formatter.default'
        - '@inventis_translation.fallback_catalogue_configuring_message_catalogue_factory'
        - '@inventis_translation.doctrine_translation_storage_querier'
        - '@inventis_translation.doctrine_translation_storage_updater'
        - '@inventis_translation.message_catalogue_cache_refresher'

    inventis_translation.doctrine_resource:
        class: Inventis\Bundle\TranslationBundle\DoctrineResource
        arguments:
        - Inventis\Bundle\TranslationBundle\Entity\TranslationKeyTranslation
        - 300

    inventis_translation.fallback_catalogue_configuring_message_catalogue_factory:
        class: Inventis\Bundle\TranslationBundle\FallbackCatalogueConfiguringMessageCatalogueFactory
        decorates: inventis_translation.cached_doctrine_message_catalogue
        arguments:
        - '@inventis_translation.fallback_catalogue_configuring_message_catalogue_factory.inner'
