inventis_navigation:
    menus:
        # these will get translated
        - { title: 'menu.main', alias: 'main' }
        - { title: 'menu.footer', alias: 'footer' }

cmf_core:
    persistence:
        phpcr: ~
