services:
    inventis.media.builder.media_preview_builder:
        class: Inventis\Bundle\MediaBundle\BrickBuilder\MediaPreviewBuilder
        arguments:
            - '@inventis.media.context_formats_provider'
        tags:
            - {name: inventis.bricks.brick_builder}

    inventis.media.builder.media_overview_builder:
        class: Inventis\Bundle\MediaBundle\BrickBuilder\MediaOverviewBuilder
        arguments:
            - '@sonata.media.pool'
        tags:
            - {name: inventis.bricks.brick_builder}

    inventis.media.builder.image_upload_button_builder:
        class: Inventis\Bundle\MediaBundle\BrickBuilder\ImageUploadButtonBuilder
        arguments:
            - '@security.csrf.token_manager'
            - '%form.type_extension.csrf.field_name%'
        tags:
            - {name: inventis.bricks.brick_builder}

    inventis.media.media_grid_builder:
        class: Inventis\Bundle\MediaBundle\BrickBuilder\MediaGridBuilder
        arguments:
            - '@router'
        tags:
            - {name: inventis.bricks.brick_builder}

    inventis.media.media_selection_overview_builder:
        class: Inventis\Bundle\MediaBundle\BrickBuilder\MediaSelectionOverviewBuilder
        arguments:
            - '@router'
        tags:
            - {name: inventis.bricks.brick_builder}

    inventis.media.media_selection_capable_form_builder:
        class: Inventis\Bundle\MediaBundle\BrickBuilder\MediaSelectionCapableFormBuilder
        arguments:
            - '@inventis.bricks.builders.event_routing_placeholder_mapper'
        tags:
            - {name: inventis.bricks.brick_builder}
