inventis_form:
    classes:
        form: App\Entity\Form\Form
        form_field: App\Entity\Form\FormField
        form_field_translation: App\Entity\Form\FormFieldTranslation
        form_field_choice: App\Entity\Form\FormFieldChoice
        form_field_choice_translation: App\Entity\Form\FormFieldChoiceTranslation
        form_submission: App\Entity\Form\FormSubmission
        form_submission_answer: App\Entity\Form\FormSubmissionAnswer
        form_translation: App\Entity\Form\FormTranslation
        form_receiver: App\Entity\Form\FormReceiver
    blocks:
        form:
            name: 'styleguide.block.form.name'
            group: 'styleguide.blocks-group.element.name'
            sequence: 3013
            template: '@InventisForm/rows/form/form.html.twig'
            preview_image: '/bundles/inventisform/assets/preview-images/form.svg'
            translation_domain: 'InventisFormBundle'
            js_module: 'Inventis/Bundle/FormBundle/Block/FormPlugin'
            factory: 'inventis_form.block.form_block_provider_factory'
