# Read the documentation: https://symfony.com/doc/master/cmf/bundles/seo/configuration.html
cmf_seo:
    persistence:
        phpcr: true
    title: '%%content_title%% | Insert your base Title'
    description: '%%content_description%% Insert you base description here.'

sonata_seo:
    page:
        separator: ' – '
        title: "Inventis Webadmin"
