doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            connection: default
            caches:
                meta: doctrine_cache.providers.phpcr_meta
                nodes: doctrine_cache.providers.phpcr_nodes
            parameters:
                jackalope.check_login_on_server: false
        workspace: '%env(PHPCR_WORKSPACE)%'
        username: '%env(PHPCR_USER)%'
        password: '%env(PHPCR_PASSWORD)%'
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        locale_chooser: doctrine_phpcr.odm.locale_chooser
        default_locale: '%locale%'
        locales:
            nl_BE: []
doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system
