inventis_navigation:
    menus:
        # these will get translated
        - { title: 'menu.main', alias: 'main' }
        - { title: 'menu.meta', alias: 'meta' }
        - { title: 'menu.footer', alias: 'footer' }
        - { title: 'menu.legal', alias: 'legal' }

cmf_core:
    persistence:
        phpcr: ~
