inventis_mediabundle_routing:
    resource: "@InventisMediaBundle/Controller/Webadmin"
    type: annotation
    prefix: /webadmin/mediabundle

inventis_mediabundle_feature_routing:
    resource: "@InventisMediaBundle/Features/Controller/"
    type: annotation
    prefix: /mediabundle
