# for more configuration settings run docker/console config:dump-reference CmfCoreBundle
cmf_core:
    multilang:
        locales: ['nl_BE']
    persistence:
        phpcr:
            enabled: true
            translation_strategy: child
