services:
# form_type extensions
    inventis.bricks.form.dynamic_form_type_extention.factory:
        class: Inventis\Bundle\BricksBundle\Form\Extension\Brick\DynamicTypeExtensionFactory
        public: true
        arguments:
            - '@inventis.bricks.form.brick_extension.auto_wire_strategy.default'
            - '@inventis.bricks.form.brick_extension.brick_builder_strategy.default'

    inventis.bricks.form.form_type_extention:
        class: Inventis\Bundle\BricksBundle\Form\Extension\Brick\DynamicTypeExtension
        public: true
        factory: ['@inventis.bricks.form.dynamic_form_type_extention.factory', 'createFormTypeExtension']
        arguments: [Symfony\Component\Form\Extension\Core\Type\FormType]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    inventis.bricks.form.data_label_form_type_extention:
        class: Inventis\Bundle\BricksBundle\Form\Extension\DataLabelFormTypeExtension
        public: true
        arguments: ['@inventis.bricks.form_extension.brick.auto_wire.view_parser.dynamic_label_parser']
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    inventis.bricks.form.choice_type_extention:
        class: Inventis\Bundle\BricksBundle\Form\Extension\Brick\DynamicTypeExtension
        public: true
        factory: ['@inventis.bricks.form.dynamic_form_type_extention.factory', 'createFormTypeExtension']
        arguments: [Symfony\Component\Form\Extension\Core\Type\ChoiceType]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

    inventis.bricks.form.button_type_extention:
        class: Inventis\Bundle\BricksBundle\Form\Extension\Brick\DynamicTypeExtension
        public: true
        factory: ['@inventis.bricks.form.dynamic_form_type_extention.factory', 'createFormTypeExtension']
        arguments: [Symfony\Component\Form\Extension\Core\Type\ButtonType]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

    inventis.bricks.form.collection_type_extention:
        class: Inventis\Bundle\BricksBundle\Form\Extension\Brick\CollectionTypeExtension
        public: true
        arguments:
            - '@inventis.bricks.form.brick_extension.auto_wire_strategy.default'
            - '@inventis.bricks.form.brick_extension.brick_builder_strategy.default'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }

    inventis.bricks.form.checkbox_type_extention:
        class: Inventis\Bundle\BricksBundle\Form\Extension\CheckboxTypeFalseValuesExtension
        public: false
        tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType }

#decorations
    inventis.bricks.csfr_extension_decorator:
        class: Inventis\Bundle\BricksBundle\Form\Extension\FormTypeCsrfExtensionDecorator
        decorates: form.type_extension.csrf
        arguments: ['@inventis.bricks.csfr_extension_decorator.inner']
        public: false
