inventis_media:
    thumbnails:
        resolver: 'default'
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType

doctrine_phpcr:
    odm:
        mappings:
            SonataMediaBundle:
                mapping: true
                type: xml
                prefix: 'Sonata\MediaBundle\PHPCR'
            InventisMediaBundle:
                mapping: true
                type: xml
                prefix: 'Inventis\Bundle\MediaBundle\PHPCR'
sonata_media:
    db_driver: doctrine_orm
    # if you don't use default namespace configuration
    class:
        media: Inventis\Bundle\MediaBundle\Entity\Media
        gallery: Inventis\Bundle\MediaBundle\Entity\Gallery
        gallery_has_media: Inventis\Bundle\MediaBundle\Entity\GalleryHasMedia
    providers:
        image:
            thumbnail: inventis.media.thumbnail.liip_imagine
            allowed_extensions: ['jpg', 'png', 'gif', 'jpeg'] # Optional
            allowed_mime_types: ['image/pjpeg','image/jpeg','image/png','image/x-png', 'image/gif'] # Optional
        vimeo:
            thumbnail: inventis.media.thumbnail.liip_imagine
        youtube:
            thumbnail: inventis.media.thumbnail.liip_imagine
        dailymotion:
            thumbnail: inventis.media.thumbnail.liip_imagine
    filesystem:
        local:
            create: true

twig:
    form_themes:
        - '@SonataMedia/Form/media_widgets.html.twig'

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: cache/media

    loaders:
        default:
            filesystem:
                data_root:
                    # this is needed for LiipImagine root path validation as public/upload is outside document root
                    # the ../ at the end is required because LiipImagine resolves the real path of the
                    # symlink. doing just public which is not a symlink would resolve in a different path inside
                    # the release folder, please note that because of the ../ you SHOULD NOT put the upload dir directly under
                    # the shared directy, because then technically the whole shared directory is made accessible by LiipImagine
                    # this can be solved by putting pulic shared files in someting like shared/public/upload  outside your release
                    # and symlink to that file
                    - '%kernel.project_dir%/public/upload/..'
            gaufrette:
                filesystem: 'sonata.media.filesystem.local' # must match sonata_media.filesystem
    filter_sets:
        # these must match <context>_<format> options of your sonata media context
        default_small:
            quality: 75
            filters:
                thumbnail: { size: [100, 70], mode: outbound }
        default_big:
            quality: 75
            filters:
                thumbnail: { size: [500, 70], mode: outbound }

jms_serializer:
    metadata:
        directories:
            SonataMedia:
                namespace_prefix: "Sonata\\MediaBundle"
                path: "@InventisMediaBundle/Resources/config/serializer/SonataMedia"

framework:
    validation:
        enabled: true
