# for more configuration settings run docker/console config:dump-reference CmfCoreBundle
cmf_core:
    multilang:
        locales: '%supported_locales%'
    persistence:
        phpcr:
            enabled: true
            translation_strategy: child

jms_i18n_routing:
    default_locale: '%locale%'
    locales: '%supported_locales%'
    strategy: prefix

cmf_routing:
    chain:
        routers_by_id:
            #router.default: 200
            jms_i18n_routing.router: 150
            cmf_routing.dynamic_router: 100
        replace_symfony_router: true
    dynamic:
        persistence:
            phpcr:
                enabled: true
                route_basepaths:
                    - '/cms/routes'
        match_implicit_locale: true
        default_controller: 'inventis.bundle.contentbundle.controller.front.contentcontroller:indexAction'
        controllers_by_class:
            Symfony\Cmf\Component\Routing\RedirectRouteInterface: cmf_routing.redirect_controller:redirectAction

jms_serializer:
    metadata:
        directories:
            SymfonyCmfRouting:
                namespace_prefix: 'Symfony\Cmf\Bundle\RoutingBundle'
                path: "@InventisContentBundle/Resources/config/serializer/SymfonyCmfRouting"

inventis_content:
    phpcr_namespaces:
        app:
            prefix: app
            uri: https://app.inventis.be
    phpcr_route_base_path_format: '%inventis_content.phpcr_basepath%/<namespace>:routes'
    phpcr_active_namespace: app