parameters:
    supported_locales: ['nl_BE']
    env(ENABLE_BRICK_DEBUGGING): '%kernel.debug%'

inventis_bricks:
    supported_locales: '%supported_locales%'

kphoen_rulerz:
    targets:
        doctrine: true

framework:
    # templating is added to support older twig path notations Bundle:Path:Template
    # Currently symfony CmfCoreBundle still uses an old path like this
    templating: { engines: ['twig'] }

jms_serializer:
    property_naming:
        # why this isn't the default in the bundle elides me, I understand why it may not be the default for jms, but...
        id: 'jms_serializer.identical_property_naming_strategy'

twig:
    globals:
        enable_brick_debugging: '%env(ENABLE_BRICK_DEBUGGING)%'
