security:
    # https://symfony.com/doc/current/security/authenticator_manager.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        db_user_provider:
            entity:
                class: Inventis\Bundle\WebadminBundle\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        webadmin:
            pattern: '^(/[a-z]{2}(_|-)[A-Z]{2})?/webadmin'
            provider: db_user_provider
            user_checker: inventis.webadmin.user.checker
            context: webadmin
            # This is the default WebAdmin login form.
            form_login:
                login_path: inventis_webadmin_login
                check_path: inventis_webadmin_login_check
                enable_csrf: true
                csrf_token_id: webadmin_login
                default_target_path: 'inventis_webadmin'
                use_referer: true
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 86400 # 1 Day
                path: /
                domain: ~
                name: webadminLoginRememberMe
            logout:
                path: inventis_webadmin_logout
                target: inventis_webadmin
        main:
            # main firewall required for webadmin preview mode
            lazy: true
            provider: db_user_provider
            user_checker: inventis.webadmin.user.checker
            context: webadmin
            form_login:
                login_path: inventis_webadmin_login
                check_path: inventis_webadmin_login_check
                enable_csrf: true
                csrf_token_id: webadmin_login
                default_target_path: inventis_webadmin
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 86400 # 1 Day
                path: /
                domain: ~
                name: webadminLoginRememberMe

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '^(/[a-z]{2}(_|-)[A-Z]{2})?/webadmin(?!/login)', roles: ROLE_ACCESS_WEBADMIN }
